from dash import html

layout = html.Div([
    html.H1("WELCOME!", style={'text-align': 'center', 'color': '#00203FFF', 'font-family': 'Arial, sans-serif'}),
    html.H1("Please click a link above to view the desired analysis", style={'text-align': 'center', 'color': '#00203FFF', 'font-family': 'Arial, sans-serif', 'font-size': '18px'}),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
    html.Br(),
])